name: Node CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - uses: andresz1/size-limit-action@v1.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_step: install
    - name: npm lint, build, test, and size
      run: |
        npm run lint
        npm run build --if-present
        npm test
        npm run size
      env:
        CI: true
